//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dodatna_oprema
    {
        public dodatna_oprema()
        {
            this.vozilo_dodatna_oprema = new HashSet<vozilo_dodatna_oprema>();
        }
    
        public int oprema_id { get; set; }
        public string naziv { get; set; }
        public string opis { get; set; }
    
        public virtual ICollection<vozilo_dodatna_oprema> vozilo_dodatna_oprema { get; set; }
    }
}
