//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class korisnik : osoba
    {
        public korisnik()
        {
            this.korisnik_aktivnost = new HashSet<korisnik_aktivnost>();
        }
    
        public int status_id { get; set; }
    
        public virtual ICollection<korisnik_aktivnost> korisnik_aktivnost { get; set; }
        public virtual korisnik_status korisnik_status { get; set; }
    }
}
