//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class korisnik_aktivnost
    {
        public int korisnik_id { get; set; }
        public int aktivnost_id { get; set; }
        public System.DateTime od { get; set; }
        public Nullable<System.DateTime> @do { get; set; }
        public bool polozeno { get; set; }
    
        public virtual aktivnost aktivnost { get; set; }
        public virtual korisnik korisnik { get; set; }
    }
}
