//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class AutoskolaEntities : DbContext
    {
        public AutoskolaEntities()
            : base("name=AutoskolaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<aktivnost> aktivnost { get; set; }
        public DbSet<dodatna_oprema> dodatna_oprema { get; set; }
        public DbSet<drzava> drzava { get; set; }
        public DbSet<grad> grad { get; set; }
        public DbSet<kategorija> kategorija { get; set; }
        public DbSet<korisnik_aktivnost> korisnik_aktivnost { get; set; }
        public DbSet<korisnik_status> korisnik_status { get; set; }
        public DbSet<osoba> osoba { get; set; }
        public DbSet<vozilo> vozilo { get; set; }
        public DbSet<vozilo_vrsta> vozilo_vrsta { get; set; }
        public DbSet<zaposlenik_vrsta> zaposlenik_vrsta { get; set; }
        public DbSet<v_korisnik> v_korisnik { get; set; }
        public DbSet<v_vozilo> v_vozilo { get; set; }
        public DbSet<v_zaposlenik> v_zaposlenik { get; set; }
        public DbSet<vozilo_dodatna_oprema> vozilo_dodatna_oprema { get; set; }
    
        /*public virtual int CheckUserLogin(string userName, string pass, ObjectParameter roleName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CheckUserLogin", userNameParameter, passParameter, roleName);
        }*/
    }
}
