//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_korisnik
    {
        public string ime { get; set; }
        public string prezime { get; set; }
        public string oib { get; set; }
        public System.DateTime nadnevak_rod { get; set; }
        public string adresa { get; set; }
        public string naziv { get; set; }
        public string status { get; set; }
    }
}
