//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vozilo_dodatna_oprema
    {
        public int vozilo_id { get; set; }
        public int oprema_id { get; set; }
    
        public virtual dodatna_oprema dodatna_oprema { get; set; }
        public virtual vozilo vozilo { get; set; }
    }
}
