//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zaposlenik_vrsta
    {
        public zaposlenik_vrsta()
        {
            this.zaposlenik = new HashSet<zaposlenik>();
        }
    
        public int vrsta_id { get; set; }
        public string naziv { get; set; }
        public string opis { get; set; }
    
        public virtual ICollection<zaposlenik> zaposlenik { get; set; }
    }
}
